### ISSUE TITLE
Get Image Name and Text Values from Zones

### ISSUE THREAD

**Issue by iosdroid** [martin-magakian/DragAndDrop-onZone#2]
its possible to get image name and text values from dropped zone view.

**Comment by martin-magakian** [comment]
Yes, from your a "ZoneView" you can access "currentDragableView": the current item dropped in the zone.
From this "DragableView" you can access the "content" who is a UIView.
UIView *myLabelScalableView = myZoneView.currentDragableView.content

Cast the UIView into the type of your container
In my exemple I should cast it into "LabelScalableView" or "ImageScalableView".
((LabelScalableView *)myLabelScalableView).text

**Comment by iosdroid** [comment]
it will work  after dropping the object to zone view?

**Comment by martin-magakian** [comment]
Only after you dropped the view into the "ZoneView" you can access the "currentDragableView".
You can also access it using the "correctDragableView" who is always set.

You can also read the code here:
https://github.com/martin-magakian/DragAndDrop-onZone/blob/master/DragAndDrop/ViewController.m

**Comment by iosdroid** [comment]
Thanks its working.. I follow the instructions i got it.but its only return the image data. I need image name its possible

**Comment by martin-magakian** [comment]
Because you can't get the name of the image from an UIImageView
http://stackoverflow.com/questions/10279314/how-to-get-image-name-used-in-an-uiimage

You will need to change the code in order to keep the name of the image as a NSString

**Comment by iosdroid** [comment]
Ok.When I drag the image from scrollview. I keep the name of the image as NSString. its correct
