### ISSUE TITLE
its possible change the scroll view horizontally?

### ISSUE THREAD

**Issue by iosdroid** [martin-magakian/DragAndDrop-onZone#3]
I want to change the scrollview horizontally? where we can do it

**Comment by martin-magakian** [comment]
I don't know.
I can't answer all your questions.

Try to ask on a QA forum such as stackoverflow.com

**Comment by iosdroid** [comment]
sorry for all.Thanks for your help

**Comment by iosdroid** [comment]
sorry for all.. thanks for your valuable reply

**Comment by martin-magakian** [comment]
no problem @iosdroid
I hope my code will help you for your own project :-)
