### ISSUE TITLE
Load Images into some zones at view did load?

### ISSUE THREAD

**Issue by harryjordan** [martin-magakian/DragAndDrop-onZone#4]
Its possible to load some  images or label on view did load and also disable the image and label in the scrollview  any methods are available in your class?

Thanks

**Comment by martin-magakian** [comment]
I'm not sure I understand your question.
Anyway you can edit the code and add this "disable" feature.

iosdroid  /  harryjordan (just register today)

github is not a question / answer forum. Try your chance asking on stackoverflow.com
